"""add ticket_id to notifications

Revision ID: 44c680b80c00
Revises: 2c05fe572e50
Create Date: 2026-07-01 12:49:51.919987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c680b80c00'
down_revision: Union[str, None] = '2c05fe572e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_staff_id_key', 'employees', type_='unique')
    op.create_index(op.f('ix_employees_staff_id'), 'employees', ['staff_id'], unique=True)
    op.add_column('notifications', sa.Column('ticket_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ticket_rooms_room_id_fkey', 'ticket_rooms', type_='foreignkey')
    op.drop_constraint('ticket_rooms_ticket_id_fkey', 'ticket_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_rooms', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ticket_rooms', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_rooms', type_='foreignkey')
    op.drop_constraint(None, 'ticket_rooms', type_='foreignkey')
    op.create_foreign_key('ticket_rooms_ticket_id_fkey', 'ticket_rooms', 'tickets', ['ticket_id'], ['id'])
    op.create_foreign_key('ticket_rooms_room_id_fkey', 'ticket_rooms', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'ticket_id')
    op.drop_index(op.f('ix_employees_staff_id'), table_name='employees')
    op.create_unique_constraint('employees_staff_id_key', 'employees', ['staff_id'])
    # ### end Alembic commands ###
